name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: detect_leaks=1  # automatically detect memory leaks
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ clang

      # 3. Build and run all examples dynamically
      - name: Build and Run
        run: |
          for san in address thread undefined; do
            echo "=== Building all examples with sanitizer $san ==="
            make SANITIZE=$san
            echo "=== Running all examples with sanitizer $san ==="
            make run
          done

      - name: Clean up build artifacts
        run: |
          make clean
